trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BuildTestPackage
    displayName: Build, package
    jobs:
      - job: BuildDevVersionsJob
        displayName: Build, package
        steps:
          - task: CmdLine@2
            displayName: "Build process"
            inputs:
              script: './build.cmd CiBuild --no-logo'

          - task: PublishPipelineArtifact@1
            displayName: 'Collect build artifacts'
            inputs:
              targetPath: 'output/'
              artifactName: 'BuildPackages'
              artifactType: 'pipeline'

#          - script: dotnet tool install --global dotnet-ef
#            displayName: 'Install Entity Framework Core Tools'
#
#          - script: dotnet ef database update --project Backend/Backend.csproj --connection "Server=tcp:farligtigermovies.database.windows.net,1433;Initial Catalog=movies;Persist Security Info=False;User ID=serverAdmin;Password=Hejhej123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
#            displayName: 'Update database'
