trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BuildTestPackage
    displayName: Build, package
    jobs:
      - job: BuildDevVersionsJob
        displayName: Build, package
        steps:

          - task: CmdLine@2
            displayName: "Build process"
            inputs:
              script: './build.cmd Compile --no-logo'

          - script: |
              echo 'Creating directory if it does not exist'
              mkdir "$(Build.ArtifactStagingDirectory)\output\publish"
            displayName: 'Ensure Output Directory Exists'

          - script: |
              echo 'Listing directory contents'
              ls "$(Build.ArtifactStagingDirectory)\output\publish"
            displayName: 'List Output Directory Contents'
            
          - task: PublishPipelineArtifact@1
            displayName: 'Collect build artifacts'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/output/publish'
              artifactName: 'BuildPackages'
              artifactType: 'pipeline'

  - stage: DeployToAzure
    displayName: Deploy to Azure
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#    condition: and(succeeded(), eq(variables['Build.SourceBranch']))

    dependsOn: BuildTestPackage
    jobs:
      - job: DeployBackendVersion
        displayName: Deploy Backend to Azure App Service
        steps:

          - checkout: self
            persistCredentials: true

          - task: DownloadPipelineArtifact@2
            displayName: 'Download backend artifacts'
            inputs:
              source: 'current'
              artifactName: 'BuildPackages'
              targetPath: output/Publish

          - task: AzureCLI@2
            displayName: "Deploy backend to Azure App Service"
            inputs:
              azureSubscription: $(AzureSubscriptionId)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp deployment source config-zip --src "output/Publish/Backend.zip" --name $(AzureAppServiceBackendName) --resource-group $(AzureResourceGroupName)

      - job: DeployFrontendVersion
        displayName: Deploy Frontend to Azure App Service
        steps:

          - checkout: self
            persistCredentials: true

          - task: DownloadPipelineArtifact@2
            displayName: 'Download frontend artifacts'
            inputs:
              source: 'current'
              artifactName: 'BuildPackages'
              targetPath: output/Publish

          - task: AzureCLI@2
            displayName: "Deploy frontend to Azure App Service"
            inputs:
              azureSubscription: $(AzureSubscriptionId)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp deployment source config-zip --src "output/Publish/Frontend.zip" --name $(AzureAppServiceFrontendName) --resource-group $(AzureResourceGroupName)
