trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

stages:

  - stage: BuildTestPackage
    displayName: Build, test, package
    jobs:
      - job: BuildDevVersionsJob
        displayName: Build, test, package
        steps:

          - task: CmdLine@2
            displayName: "Build and test process"
            inputs:
              script: './build.cmd Compile Test --no-logo'

          - task: PublishPipelineArtifact@1
            displayName: 'Collect build artifacts'
            inputs:
              targetPath: output/
              artifactName: 'BuildPackages'
              artifactType: 'pipeline'

          - task: PublishBuildArtifacts@1
            displayName: "Collect test artifacts"
            inputs:
              artifactName: TestArtifact
              pathtoPublish: 'output/TestResults'

          - task: PublishTestResults@2
            displayName: "Publish test results"
            condition: always()
            inputs:
              testResultsFormat: 'XUnit'
              testResultsFiles: 'output/TestResults/*.xml'
              failTaskOnFailedTests: true

  - stage: DeployToAzure
    displayName: Deploy to Azure
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: BuildTestPackage
    jobs:
      - job: DeployProductionVersion
        displayName: Deploy to Azure App Service
        steps:

          - checkout: self
            persistCredentials: true

          - task: DownloadPipelineArtifact@2
            displayName: 'Download pipeline artifacts'
            inputs:
              source: 'current'
              artifactName: 'BuildPackages'
              targetPath: output/

          - task: CmdLine@2
            displayName: "Deploy to Azure App Service"
            env:
              AZURE_SUBSCRIPTION_ID: $(AzureSubscriptionId)
              AZURE_RESOURCE_GROUP_NAME: $(AzureResourceGroupName)
              AZURE_APP_SERVICE_NAME: $(AzureAppServiceName)
            inputs:
              script: './build.cmd Deploy --no-logo'
