// <auto-generated />
using System;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230525220622_addingIndexToPersonTable")]
    partial class addingIndexToPersonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Movie.Infrastructure.Models.MovieDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Title");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Backend.Movie.Infrastructure.Models.PersonDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Backend.Movie.Infrastructure.Models.RatingDAO", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Backend.People.Infrastructure.Models.PeopleDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Backend.People.Infrastructure.Models.PeopleMovieDAO", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovieId");

                    b.ToTable("PeopleMovieDAO");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.ActivityDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewRating")
                        .HasColumnType("int");

                    b.Property<int?>("OldRating")
                        .HasColumnType("int");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewBody")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("ActivityDAO");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.CommentDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostDAOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostDAOId");

                    b.ToTable("CommentDAO");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.PostDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeOfActivity")
                        .HasColumnType("datetime2");

                    b.Property<int>("Topic")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.ReactionEntryDAO", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeOfReaction")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("ReactionEntryDAO");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.SocialUserDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("SocialUsers");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserMovieDAO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeMovieWasAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMovieDAO");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserRatingDAO", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfStars")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRatingDAO");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserReviewDAO", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReviewDAO");
                });

            modelBuilder.Entity("MovieDAOPersonDAO", b =>
                {
                    b.Property<string>("ActedMoviesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActorsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActedMoviesId", "ActorsId");

                    b.HasIndex("ActorsId");

                    b.ToTable("Actors", (string)null);
                });

            modelBuilder.Entity("MovieDAOPersonDAO1", b =>
                {
                    b.Property<string>("DirectedMoviesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DirectorsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DirectedMoviesId", "DirectorsId");

                    b.HasIndex("DirectorsId");

                    b.ToTable("Directors", (string)null);
                });

            modelBuilder.Entity("PeopleDAOPeopleMovieDAO", b =>
                {
                    b.Property<string>("ActedMoviesMovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActorsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActedMoviesMovieId", "ActorsId");

                    b.HasIndex("ActorsId");

                    b.ToTable("ActedMovies", (string)null);
                });

            modelBuilder.Entity("PeopleDAOPeopleMovieDAO1", b =>
                {
                    b.Property<string>("DirectedMoviesMovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DirectorsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DirectedMoviesMovieId", "DirectorsId");

                    b.HasIndex("DirectorsId");

                    b.ToTable("DirectedMovies", (string)null);
                });

            modelBuilder.Entity("SocialUserFollowers", b =>
                {
                    b.Property<string>("FollowingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FollowingId", "FollowerId");

                    b.HasIndex("FollowerId");

                    b.ToTable("SocialUserFollowers");
                });

            modelBuilder.Entity("Backend.Movie.Infrastructure.Models.RatingDAO", b =>
                {
                    b.HasOne("Backend.Movie.Infrastructure.Models.MovieDAO", null)
                        .WithOne("Rating")
                        .HasForeignKey("Backend.Movie.Infrastructure.Models.RatingDAO", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.ActivityDAO", b =>
                {
                    b.HasOne("Backend.Social.Infrastructure.Models.PostDAO", "PostThisBelongsTo")
                        .WithOne("ActivityData")
                        .HasForeignKey("Backend.Social.Infrastructure.Models.ActivityDAO", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostThisBelongsTo");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.CommentDAO", b =>
                {
                    b.HasOne("Backend.Social.Infrastructure.Models.PostDAO", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostDAOId");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.ReactionEntryDAO", b =>
                {
                    b.HasOne("Backend.Social.Infrastructure.Models.PostDAO", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserMovieDAO", b =>
                {
                    b.HasOne("Backend.User.Infrastructure.Models.UserDAO", "User")
                        .WithMany("FavoriteMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserRatingDAO", b =>
                {
                    b.HasOne("Backend.User.Infrastructure.Models.UserDAO", "User")
                        .WithMany("UserRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserReviewDAO", b =>
                {
                    b.HasOne("Backend.User.Infrastructure.Models.UserDAO", "User")
                        .WithMany("UserReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieDAOPersonDAO", b =>
                {
                    b.HasOne("Backend.Movie.Infrastructure.Models.MovieDAO", null)
                        .WithMany()
                        .HasForeignKey("ActedMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Movie.Infrastructure.Models.PersonDAO", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieDAOPersonDAO1", b =>
                {
                    b.HasOne("Backend.Movie.Infrastructure.Models.MovieDAO", null)
                        .WithMany()
                        .HasForeignKey("DirectedMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Movie.Infrastructure.Models.PersonDAO", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleDAOPeopleMovieDAO", b =>
                {
                    b.HasOne("Backend.People.Infrastructure.Models.PeopleMovieDAO", null)
                        .WithMany()
                        .HasForeignKey("ActedMoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.People.Infrastructure.Models.PeopleDAO", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleDAOPeopleMovieDAO1", b =>
                {
                    b.HasOne("Backend.People.Infrastructure.Models.PeopleMovieDAO", null)
                        .WithMany()
                        .HasForeignKey("DirectedMoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.People.Infrastructure.Models.PeopleDAO", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialUserFollowers", b =>
                {
                    b.HasOne("Backend.Social.Infrastructure.Models.SocialUserDAO", null)
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Backend.Social.Infrastructure.Models.SocialUserDAO", null)
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Movie.Infrastructure.Models.MovieDAO", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Backend.Social.Infrastructure.Models.PostDAO", b =>
                {
                    b.Navigation("ActivityData");

                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Backend.User.Infrastructure.Models.UserDAO", b =>
                {
                    b.Navigation("FavoriteMovies");

                    b.Navigation("UserRatings");

                    b.Navigation("UserReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
